### ISSUE TITLE
Download in high quality 

### ISSUE THREAD

**Issue by qchenac** [vikas5914/Facebook-Video-Downloader#40]
For now, it just support low quality video download. It seems that facebook prevents you from downloading highest quality of their videos. I am not sure if there is any way to crack it.

**Comment by vikas5914** [comment]
@qchenac Facebook doesn't prevent you. You can scrap those links. The problem is that those links don't have audio in them. 

So you have to download the video and audio separately and combine them using FFmpeg. So I don't want to download anything to my server; this code skips that part and only provides the SD and HD links.
