### ISSUE TITLE
Error retrieving the download link for the url!

### ISSUE THREAD

**Issue by NoorQureshi** [vikas5914/Facebook-Video-Downloader#6]
> Error retrieving the download link for the url. Please try again later

Not working again mate! It would be awesome if you update your code! 

**Thank you!**

**Comment by vikas5914** [comment]
I know .. but currently busy with lots of work. I will try to update this weekends

**Comment by matthew-asuncion** [comment]
You can use this URL to get Facebook video URL for fb pages only. It may not work for private or profile videos. 

https://graph.facebook.com/10154929511829759/

It will output video source in json. I have tried it here [www.getfbvideos.com](https://www.getfbvideos.com)

**Comment by vikas5914** [comment]
Because of Profile and Private video. I didn't use Graph API in this code. 

Thanks for reminding me about graph API . I will add that in next version.

**Comment by MusaSiddiqui** [comment]
@matthew-asuncion please share the script of getfbvideos.com or solve the issues of this script. My website is not working since last 2 months. Because I am having no experience of these codes etc. but still I tried to resolve the issues, but I failed...
@vikas5914 dear Vikas please try to solve all the issues of this script as soon as possible, because many sites are not working...

**Comment by vikas5914** [comment]
@MusaSiddiqui  Sorry for the really late response. I was able to fix the code. 

https://github.com/vikas5914/Facebook-Video-Downloader/commit/68f38c011446a4e33285f18fa81b1de828fb4f6c
